language: objective-c
osx_image: xcode8.2
rvm: 2.0.0

env:
  global:
   - ADB_INSTALL_TIMEOUT=10
   - LICENSES="android-sdk-license-5be876d5|mips-android-sysimage-license-15de68cc|intel-android-sysimage-license-1ea702d1|android-sdk-license-ed0d0a5b|android-sdk-license-c81a61d9"
   - COMPONENTS=build-tools-25.0.1,android-25,extra-android-m2repository,extra-google-m2repository
  matrix:
    - PLATFORM=iOS
    - PLATFORM=Android
    - DANGER=1

cache:
  directories:
    - $HOME/android/library/.gradle/

podfile: ios/Framework
before_script:
 - |
   if [ "$PLATFORM" = Android ]; then
        curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-2/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS --accept=$LICENSES && source ~/.android-sdk-installer/env
   fi
 
script:
- |
   if [ "$PLATFORM" = Android ]; then
        cd android
        sh gradlew clean
        sh gradlew assembleTravisci
        sh gradlew test
     elif [ "$PLATFORM" = iOS ]; then
         cd ios/Framework
         pod install --repo-update
         set -o pipefail
         xcodebuild clean build build-for-testing -workspace LiferayScreens.xcworkspace -scheme LiferayScreens -destination "id=E40727B3-41FB-4D6E-B4CB-BFA87109EB12" | xcpretty
         xcodebuild test-without-building -workspace LiferayScreens.xcworkspace -scheme LiferayScreens -destination "id=E40727B3-41FB-4D6E-B4CB-BFA87109EB12" | xcpretty
    elif [ "${DANGER}" -eq 1 ]; then
         gem install danger --version '~> 4.0' && danger
    fi